ARG SERVER_PORT
ARG REDIS_SERVER_URL
ARG HUBSPOT_CLIENT_ID
ARG HUBSPOT_CLIENT_SECRET
ARG ZOHOCRM_CLIENT_ID
ARG ZOHOCRM_CLIENT_SECRET
ARG PGSQL_URL
ARG SFDC_CLIENT_ID
ARG SFDC_CLIENT_SECRET
ARG OAUTH_REDIRECT_BASE
ARG FERN_TOKEN
ARG PORT

FROM node:alpine
WORKDIR /app/
COPY . /app/

RUN echo ${PGSQL_URL}
ENV SERVER_PORT ${SERVER_PORT}
ENV REDIS_SERVER_URL ${REDIS_SERVER_URL}
ENV HUBSPOT_CLIENT_ID ${HUBSPOT_CLIENT_ID}
ENV HUBSPOT_CLIENT_SECRET ${HUBSPOT_CLIENT_SECRET}
ENV ZOHOCRM_CLIENT_ID ${ZOHOCRM_CLIENT_ID}
ENV ZOHOCRM_CLIENT_SECRET ${ZOHOCRM_CLIENT_SECRET}
ENV PGSQL_URL ${PGSQL_URL}
ENV SFDC_CLIENT_ID ${SFDC_CLIENT_ID}
ENV SFDC_CLIENT_SECRET ${SFDC_CLIENT_SECRET}
ENV OAUTH_REDIRECT_BASE ${OAUTH_REDIRECT_BASE}
ENV PORT ${PORT}
ENV FERN_TOKEN ${FERN_TOKEN}

# create .env from the vars passed.
RUN cat > .env <<EOF 
SERVER_PORT=$SERVER_PORT
REDIS_SERVER_URL=$REDIS_SERVER_URL
HUBSPOT_CLIENT_ID=$HUBSPOT_CLIENT_ID
HUBSPOT_CLIENT_SECRET=$HUBSPOT_CLIENT_SECRET
ZOHOCRM_CLIENT_ID=$ZOHOCRM_CLIENT_ID
ZOHOCRM_CLIENT_SECRET=$ZOHOCRM_CLIENT_SECRET
PGSQL_URL=$PGSQL_URL
SFDC_CLIENT_ID=$SFDC_CLIENT_ID
SFDC_CLIENT_SECRET=$SFDC_CLIENT_SECRET
OAUTH_REDIRECT_BASE=$OAUTH_REDIRECT_BASE
PORT=$PORT
FERN_TOKEN=$FERN_TOKEN
EOF

RUN npm install -g npm@9.6.5
RUN yarn install --check-cache
RUN ls && npm install -g fern-api@0.6.12 && fern -v && fern generate --log-level debug
RUN yarn workspace @revertdotdev/backend build
CMD ["node", "./packages/backend/dist/index.js"]