import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { RevertConnect } from '@/lib';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                Revert Demo
                <RevertConnect
                    config={{
                        revertToken: 'pk_test_Y2xlcmsuc3Ryb25nLmRlZXItNTYubGNsLmRldiQ',
                        tenantId: 'testTenantId',
                    }}
                />
            </main>
        </>
    );
}
